# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scalable CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        cache: maven

    - name: Build and Package with Maven
      run: wget https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar
      
    - name: Build and Package with Maven
      #run: wget https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar
      run: mvn -B package --file pom.xml && ls -la /home/runner/work/scalablej/scalablej/target
 
    - name: Executing Scala Program (shaded)
      run: java -cp target/scalablej-1.0-SNAPSHOT-shaded.jar com.scalablej.core.starter
      
    - name: Executing Java Program (shaded)
      run: java -cp target/scalablej-1.0-SNAPSHOT-shaded.jar com.scalablej.core.startup
   
    - name: Executing Java Program
      run: java -cp scala-library-2.12.5.jar -jar target/scalablej-1.0-SNAPSHOT.jar com.scalablej.core.startup

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
